### ISSUE TITLE
Chinese ?

### ISSUE THREAD

**Issue by am1006** [luochenzhimu/MathType#1]

**Comment by luochenzhimu** [comment]
The Windows version have translated into Chinese.

**Comment by am1006** [comment]
Thanks.
So you have done the translation work?
And will you update it when a new version comes out?

**Comment by luochenzhimu** [comment]
@am1006 Not Yet, I am working on how to re-package the Mac version, but I have no idea. 
Only a few years the official release a version and absolutely I will update it!

**Comment by am1006** [comment]
Yeah. Quite a good job.
Appreciate it.
The mac version is _absolutely_ A problem.
So the translation , I guess, comes from the official simplified version.Right?
No offence.

**Comment by luochenzhimu** [comment]
@am1006 Why are you so interested about it？If you don't use it,  it make no sense to you. 
I translate it word by word, and if you have any comments or disagreements, I can fix it including the deletion of this translation.
